name: photogear_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  toggle_switch: ^2.1.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dotted_border: ^2.0.0+3
  flutter_credit_card: ^3.0.7
  smooth_page_indicator: ^1.1.0
  animated_splash_screen: ^1.3.0
  flutter_localization: ^0.1.14
  flutter_screenutil: ^5.9.3
  introduction_screen: ^3.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.0


flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/shared/
    - assets/images/categories/
    - assets/images/cameras/
    - assets/images/lenses/
    - assets/images/memorise/
    - assets/images/bags/
    - assets/images/drones/
    - assets/images/on_boarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
        - asset: assets/fonts/NotoNaskhArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoNaskhArabic-SemiBold.ttf
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
